export const topics = [
{
  name: '感情 — Kanjō — Emotions',
  wordsAndImages: [
    { en: 'happy', fi: 'ureshii (うれしい)', img: 'emotions/happy.png' },
    { en: 'excited', fi: 'koufun shiteiru (興奮している)', img: 'emotions/excited.png' },
    { en: 'proud', fi: 'hokori takai (誇り高い)', img: 'emotions/proud.png' },
    { en: 'in love', fi: 'koishiteiru (恋している)', img: 'emotions/inlove.png' },
    { en: 'grateful', fi: 'kansha shiteiru (感謝している)', img: 'emotions/grateful.png' },
    { en: 'confident', fi: 'jishin ga aru (自信がある)', img: 'emotions/confident.png' },
    { en: 'sad', fi: 'kanashii (悲しい)', img: 'emotions/sad.png' },
    { en: 'angry', fi: 'okotteiru (怒っている)', img: 'emotions/angry.png' },
    { en: 'scared', fi: 'kowagatteiru (怖がっている)', img: 'emotions/scared.png' },
    { en: 'embarrassed', fi: 'hazukashii (恥ずかしい)', img: 'emotions/embarrassed.png' },
    { en: 'frustrated', fi: 'iradatteshiteiru (苛立ってしている)', img: 'emotions/frustrated.png' },
    { en: 'surprised', fi: 'odoraita (驚いた)', img: 'emotions/surprised.png' }
  ]
},
{
  name: '動物 — Dōbutsu — Animals',
  wordsAndImages: [
    { en: 'bear', fi: 'kuma (熊)', img: 'animals/bear.png' },
    { en: 'bee', fi: 'hachi (蜂)', img: 'animals/bee.png' },
    { en: 'bird', fi: 'tori (鳥)', img: 'animals/bird.png' },
    { en: 'butterfly', fi: 'chou (蝶)', img: 'animals/butterfly.png' },
    { en: 'cat', fi: 'neko (猫)', img: 'animals/cat.png' },
    { en: 'chicken', fi: 'niwatori (鶏)', img: 'animals/chicken.png' },
    { en: 'cow', fi: 'ushi (牛)', img: 'animals/cow.png' },
    { en: 'dog', fi: 'inu (犬)', img: 'animals/dog.png' },
    { en: 'elephant', fi: 'zou (象)', img: 'animals/elephant.png' },
    { en: 'fish', fi: 'sakana (魚)', img: 'animals/fish.png' },
    { en: 'fly', fi: 'hae (蠅)', img: 'animals/fly.png' },
    { en: 'horse', fi: 'uma (馬)', img: 'animals/horse.png' },
    { en: 'lion', fi: 'raion (ライオン)', img: 'animals/lion.png' },
    { en: 'mosquito', fi: 'ka (蚊)', img: 'animals/mosquito.png' },
    { en: 'mouse', fi: 'nezumi (鼠)', img: 'animals/mouse.png' },
    { en: 'pig', fi: 'buta (豚)', img: 'animals/pig.png' },
    { en: 'rabbit', fi: 'usagi (兎)', img: 'animals/rabbit.png' },
    { en: 'rat', fi: 'nezumi (鼠)', img: 'animals/rat.png' },
    { en: 'seagull', fi: 'kamome (かもめ)', img: 'animals/seagull.png' },
    { en: 'sheep', fi: 'hitsuji (羊)', img: 'animals/sheep.png' }
  ]
},


{
  name: '食べ物 — Tabemono — Food',
  wordsAndImages: [
    { en: 'bread', fi: 'pan (パン)', img: 'food/bread.png' },
    { en: 'butter', fi: 'bataa (バター)', img: 'food/butter.png' },
    { en: 'carrot', fi: 'ninjin (人参)', img: 'food/carrot.png' },
    { en: 'cheese', fi: 'chiizu (チーズ)', img: 'food/cheese.png' },
    { en: 'cucumber', fi: 'kyūri (きゅうり)', img: 'food/cucumber.png' },
    { en: 'egg', fi: 'tamago (卵)', img: 'food/egg.png' },
    { en: 'garlic', fi: 'ninniku (にんにく)', img: 'food/garlic.png' },
    { en: 'milk', fi: 'gyuunyuu (牛乳)', img: 'food/milk.png' },
    { en: 'onion', fi: 'tamanegi (玉ねぎ)', img: 'food/onion.png' },
    { en: 'pasta', fi: 'pasuta (パスタ)', img: 'food/pasta.png' },
    { en: 'potato', fi: 'jagaimo (じゃがいも)', img: 'food/potato.png' },
    { en: 'rice', fi: 'gohan (ごはん)', img: 'food/rice.png' },
    { en: 'salad', fi: 'sarada (サラダ)', img: 'food/salad.png' },
    { en: 'soup', fi: 'suupu (スープ)', img: 'food/soup.png' },
    { en: 'yoghurt', fi: 'yōguruto (ヨーグルト)', img: 'food/yoghurt.png' }
  ]
},

{
  name: '果物 — Kudamono — Fruits',
  wordsAndImages: [
    { en: 'apple', fi: 'ringo (りんご)', img: 'fruits/apple.png' },
    { en: 'banana', fi: 'banana (バナナ)', img: 'fruits/banana.png' },
    { en: 'blueberry', fi: 'burūberī (ブルーベリー)', img: 'fruits/blueberry.png' },
    { en: 'cherry', fi: 'sakuranbo (さくらんぼ)', img: 'fruits/cherry.png' },
    { en: 'grapefruit', fi: 'gurēpufurūtsu (グレープフルーツ)', img: 'fruits/grapefruit.png' },
    { en: 'grapes', fi: 'budou (ぶどう)', img: 'fruits/grapes.png' },
    { en: 'kiwi', fi: 'kiui (キウイ)', img: 'fruits/kiwi.png' },
    { en: 'lemon', fi: 'remon (レモン)', img: 'fruits/lemon.png' },
    { en: 'lime', fi: 'raimu (ライム)', img: 'fruits/lime.png' },
    { en: 'mango', fi: 'mango (マンゴー)', img: 'fruits/mango.png' },
    { en: 'orange', fi: 'orenji (オレンジ)', img: 'fruits/orange.png' },
    { en: 'peach', fi: 'momo (もも)', img: 'fruits/peach.png' },
    { en: 'pear', fi: 'nashi (梨)', img: 'fruits/pear.png' },
    { en: 'pineapple', fi: 'painappuru (パイナップル)', img: 'fruits/pineapple.png' },
    { en: 'plum', fi: 'sumomo (すもも)', img: 'fruits/plum.png' },
    { en: 'raspberry', fi: 'razuberī (ラズベリー)', img: 'fruits/raspberry.png' },
    { en: 'strawberry', fi: 'ichigo (いちご)', img: 'fruits/strawberry.png' },
    { en: 'watermelon', fi: 'suika (スイカ)', img: 'fruits/watermelon.png' }
  ]
},


{
  name: '乗り物 — Norimono — Vehicles',
  wordsAndImages: [
    { en: 'airplane', fi: 'hikouki (飛行機)', img: 'vehicles/airplane.png' },
    { en: 'ambulance', fi: 'kyuukyuusha (救急車)', img: 'vehicles/ambulance.png' },
    { en: 'bicycle', fi: 'jitensha (自転車)', img: 'vehicles/bicycle.png' },
    { en: 'boat', fi: 'fune (船)', img: 'vehicles/boat.png' },
    { en: 'bus', fi: 'basu (バス)', img: 'vehicles/bus.png' },
    { en: 'car', fi: 'kuruma (車)', img: 'vehicles/car.png' },
    { en: 'drone', fi: 'dorōn (ドローン)', img: 'vehicles/drone.png' },
    { en: 'fire truck', fi: 'shoubousha (消防車)', img: 'vehicles/fire_truck.png' },
    { en: 'helicopter', fi: 'herikoputā (ヘリコプター)', img: 'vehicles/helicopter.png' },
    { en: 'hot air balloon', fi: 'nekki kyūkyūkyū (熱気球)', img: 'vehicles/hot_air_balloon.png' },
    { en: 'metro', fi: 'chikatetsu (地下鉄)', img: 'vehicles/metro.png' },
    { en: 'motorcycle', fi: 'baiku (バイク)', img: 'vehicles/motorcycle.png' },
    { en: 'police car', fi: 'patokaa (パトカー)', img: 'vehicles/police_car.png' },
    { en: 'taxi', fi: 'takushii (タクシー)', img: 'vehicles/taxi.png' },
    { en: 'tractor', fi: 'trakutā (トラクター)', img: 'vehicles/tractor.png' },
    { en: 'train', fi: 'densha (電車)', img: 'vehicles/train.png' },
    { en: 'tram', fi: 'romendensha (路面電車)', img: 'vehicles/tram.png' },
    { en: 'truck', fi: 'torakku (トラック)', img: 'vehicles/truck.png' },
    { en: 'van', fi: 'ban (バン)', img: 'vehicles/van.png' }
  ]
},

{
  name: '家 — Ie — Home',
  wordsAndImages: [
    { en: 'bathroom', fi: 'ofuroba (お風呂場)', img: 'home/bathroom.png' },
    { en: 'bed', fi: 'beddo (ベッド)', img: 'home/bed.png' },
    { en: 'bedroom', fi: 'shinshitsu (寝室)', img: 'home/bedroom.png' },
    { en: 'blanket', fi: 'mōfu (毛布)', img: 'home/blanket.png' },
    { en: 'carpet', fi: 'jūtan (絨毯)', img: 'home/carpet.png' },
    { en: 'ceiling', fi: 'tenjō (天井)', img: 'home/ceiling.png' },
    { en: 'chair', fi: 'isu (椅子)', img: 'home/chair.png' },
    { en: 'clock', fi: 'tokei (時計)', img: 'home/clock.png' },
    { en: 'cup', fi: 'koppu (コップ)', img: 'home/cup.png' },
    { en: 'cupboard', fi: 'tana (棚)', img: 'home/cupboard.png' },
    { en: 'dishwasher', fi: 'shokki araiki (食器洗い機)', img: 'home/dishwasher.png' },
    { en: 'door', fi: 'doa (ドア)', img: 'home/door.png' },
    { en: 'floor', fi: 'yuka (床)', img: 'home/floor.png' },
    { en: 'fork', fi: 'fōku (フォーク)', img: 'home/fork.png' },
    { en: 'fridge', fi: 'reizōko (冷蔵庫)', img: 'home/fridge.png' },
    { en: 'glass', fi: 'gurasu (グラス)', img: 'home/glass.png' },
    { en: 'home', fi: 'ie (家)', img: 'home/home.png' },
    { en: 'house', fi: 'uchi (家)', img: 'home/house.png' },
    { en: 'kitchen', fi: 'dainingu kicchin (ダイニングキッチン)', img: 'home/kitchen.png' },
    { en: 'knife', fi: 'naifu (ナイフ)', img: 'home/knife.png' },
    { en: 'lamp', fi: 'ranpu (ランプ)', img: 'home/lamp.png' },
    { en: 'light', fi: 'akarui (明かり)', img: 'home/light.png' },
    { en: 'living room', fi: 'ribingu rūmu (リビングルーム)', img: 'home/living_room.png' },
    { en: 'microwave oven', fi: 'denshi renji (電子レンジ)', img: 'home/microwave_oven.png' },
    { en: 'mirror', fi: 'kagami (鏡)', img: 'home/mirror.png' },
    { en: 'oven', fi: 'ōbun (オーブン)', img: 'home/oven.png' },
    { en: 'pillow', fi: 'makura (枕)', img: 'home/pillow.png' },
    { en: 'plate', fi: 'sara (皿)', img: 'home/plate.png' },
    { en: 'room', fi: 'heya (部屋)', img: 'home/room.png' },
    { en: 'shirt', fi: 'shatsu (シャツ)', img: 'home/shirt.png' },
    { en: 'sink', fi: 'nagashi (流し)', img: 'home/sink.png' },
    { en: 'sofa', fi: 'sofa (ソファ)', img: 'home/sofa.png' },
    { en: 'spoon', fi: 'supūn (スプーン)', img: 'home/spoon.png' },
    { en: 'stove', fi: 'sutōbu (ストーブ)', img: 'home/stove.png' },
    { en: 'table', fi: 'tēburu (テーブル)', img: 'home/table.png' },
    { en: 'television', fi: 'terebi (テレビ)', img: 'home/television.png' },
    { en: 'wall', fi: 'kabe (壁)', img: 'home/wall.png' },
    { en: 'washing machine', fi: 'sentakki (洗濯機)', img: 'home/washing_machine.png' },
    { en: 'window', fi: 'mado (窓)', img: 'home/window.png' }
  ]
},


{
  name: 'よく使う動詞 — Yoku tsukau dōshi — Common Verbs',
  wordsAndImages: [
    { en: 'drink', fi: 'nomu (飲む)', img: 'verbs1/drink.jfif' },
    { en: 'drive', fi: 'unten suru (運転する)', img: 'verbs1/drive.jfif' },
    { en: 'eat', fi: 'taberu (食べる)', img: 'verbs1/eat.jfif' },
    { en: 'give', fi: 'ageru (あげる)', img: 'verbs1/give.jfif' },
    { en: 'hear', fi: 'kiku (聞く)', img: 'verbs1/hear.jfif' },
    { en: 'laugh', fi: 'warau (笑う)', img: 'verbs1/laugh.jfif' },
    { en: 'lift', fi: 'mochiageru (持ち上げる)', img: 'verbs1/lift.jfif' },
    { en: 'listen', fi: 'kiku (聞く)', img: 'verbs1/listen.jfif' },
    { en: 'look', fi: 'miru (見る)', img: 'verbs1/look.jfif' },
    { en: 'open', fi: 'akeru (開ける)', img: 'verbs1/open.jfif' },
    { en: 'pull', fi: 'hiku (引く)', img: 'verbs1/pull.jfif' },
    { en: 'push', fi: 'osu (押す)', img: 'verbs1/push.jfif' },
    { en: 'run', fi: 'hashiru (走る)', img: 'verbs1/run.jfif' },
    { en: 'say', fi: 'iu (言う)', img: 'verbs1/say.jfif' },
    { en: 'see', fi: 'miru (見る)', img: 'verbs1/see.jfif' },
    { en: 'sit', fi: 'suwaru (座る)', img: 'verbs1/sit.jfif' },
    { en: 'sleep', fi: 'neru (寝る)', img: 'verbs1/sleep.jfif' },
    { en: 'talk', fi: 'hanasu (話す)', img: 'verbs1/talk.jfif' },
    { en: 'think', fi: 'kangaeru (考える)', img: 'verbs1/think.jfif' },
    { en: 'walk', fi: 'aruku (歩く)', img: 'verbs1/walk.jfif' },
    { en: 'want', fi: 'hoshii (欲しい)', img: 'verbs1/want.jfif' },
    { en: 'wash', fi: 'arau (洗う)', img: 'verbs1/wash.jfif' },
    { en: 'write', fi: 'kaku (書く)', img: 'verbs1/write.jfif' }
  ]
},



{
  name: 'さらに動詞 — Sara ni dōshi — More Verbs',
  wordsAndImages: [
    { en: 'blow', fi: 'fuku (吹く)', img: 'verbs2/blow.jfif' },
    { en: 'clean', fi: 'souji suru (掃除する)', img: 'verbs2/clean.jfif' },
    { en: 'cry', fi: 'naku (泣く)', img: 'verbs2/cry.jfif' },
    { en: 'dig', fi: 'horu (掘る)', img: 'verbs2/dig.jfif' },
    { en: 'draw', fi: 'kaku (描く)', img: 'verbs2/draw.jfif' },
    { en: 'fall', fi: 'ochiru (落ちる)', img: 'verbs2/fall.jfif' },
    { en: 'find', fi: 'mitsukeru (見つける)', img: 'verbs2/find.jfif' },
    { en: 'hide', fi: 'kakureru (隠れる)', img: 'verbs2/hide.jfif' },
    { en: 'hug', fi: 'daku (抱く)', img: 'verbs2/hug.jfif' },
    { en: 'jump', fi: 'tobu (跳ぶ)', img: 'verbs2/jump.jfif' },
    { en: 'kiss', fi: 'kisu suru (キスする)', img: 'verbs2/kiss.jfif' },
    { en: 'lie down', fi: 'yokoneru (横になる)', img: 'verbs2/lie_down.jfif' },
    { en: 'paint', fi: 'nurikaeru (塗り替える)', img: 'verbs2/paint.jfif' },
    { en: 'pay', fi: 'harau (払う)', img: 'verbs2/pay.jfif' },
    { en: 'plant', fi: 'ueru (植える)', img: 'verbs2/plant.jfif' },
    { en: 'ski', fi: 'sukii o suru (スキーをする)', img: 'verbs2/ski.jfif' },
    { en: 'ski downhill', fi: 'gesan sukii o suru (下山スキーをする)', img: 'verbs2/ski_downhill.jfif' },
    { en: 'smell', fi: 'kaoru (香る)', img: 'verbs2/smell.jfif' },
    { en: 'swim', fi: 'oyogu (泳ぐ)', img: 'verbs2/swim.jfif' },
    { en: 'taste', fi: 'ajiwau (味わう)', img: 'verbs2/taste.jfif' },
    { en: 'throw', fi: 'nageru (投げる)', img: 'verbs2/throw.jfif' },
    { en: 'vacuum', fi: 'soujiki o kakeru (掃除機をかける)', img: 'verbs2/vacuum.jfif' },
    { en: 'wake up', fi: 'okiru (起きる)', img: 'verbs2/wake_up.jfif' }
  ]
},

{
  name: '形容詞 — Keiyōshi — Adjectives',
  wordsAndImages: [
    { en: 'bad', fi: 'warui (悪い)', img: 'adjectives/bad.png' },
    { en: 'big', fi: 'ookii (大きい)', img: 'adjectives/big.png' },
    { en: 'black', fi: 'kuroi (黒い)', img: 'adjectives/black.png' },
    { en: 'blue', fi: 'aoi (青い)', img: 'adjectives/blue.png' },
    { en: 'brown', fi: 'chairoi (茶色い)', img: 'adjectives/brown.png' },
    { en: 'clean', fi: 'kirei (きれい)', img: 'adjectives/clean.png' },
    { en: 'cold', fi: 'samui (寒い)', img: 'adjectives/cold.png' },
    { en: 'difficult', fi: 'muzukashii (難しい)', img: 'adjectives/difficult.png' },
    { en: 'dirty', fi: 'kitanai (汚い)', img: 'adjectives/dirty.png' },
    { en: 'easy', fi: 'yasashii (易しい)', img: 'adjectives/easy.png' },
    { en: 'fast', fi: 'hayai (速い)', img: 'adjectives/fast.png' },
    { en: 'good', fi: 'ii / yoi (良い)', img: 'adjectives/good.png' },
    { en: 'green', fi: 'midori (緑)', img: 'adjectives/green.png' },
    { en: 'high', fi: 'takai (高い)', img: 'adjectives/high.png' },
    { en: 'hot', fi: 'atsui (暑い)', img: 'adjectives/hot.png' },
    { en: 'long', fi: 'nagai (長い)', img: 'adjectives/long.png' },
    { en: 'low', fi: 'hikui (低い)', img: 'adjectives/low.png' },
    { en: 'new', fi: 'atarashii (新しい)', img: 'adjectives/new.png' },
    { en: 'old', fi: 'furui (古い)', img: 'adjectives/old.png' },
    { en: 'red', fi: 'akai (赤い)', img: 'adjectives/red.png' },
    { en: 'short', fi: 'mijikai (短い)', img: 'adjectives/short.png' },
    { en: 'slow', fi: 'osoi (遅い)', img: 'adjectives/slow.png' },
    { en: 'small', fi: 'chiisai (小さい)', img: 'adjectives/small.png' },
    { en: 'warm', fi: 'atatakai (暖かい)', img: 'adjectives/warm.png' },
    { en: 'white', fi: 'shiroi (白い)', img: 'adjectives/white.png' },
    { en: 'yellow', fi: 'kiiroi (黄色い)', img: 'adjectives/yellow.png' }
  ]
},

{
  name: '服 — Fuku — Clothing',
  wordsAndImages: [
    { en: 'backpack', fi: 'randoseru / ryukku (リュック)', img: 'clothing/backpack.png' },
    { en: 'belt', fi: 'beruto (ベルト)', img: 'clothing/belt.png' },
    { en: 'boots', fi: 'buutsu (ブーツ)', img: 'clothing/boots.png' },
    { en: 'cap', fi: 'boushi / kyappu (帽子 / キャップ)', img: 'clothing/cap.png' },
    { en: 'dress', fi: 'wanpiisu (ワンピース)', img: 'clothing/dress.png' },
    { en: 'earrings', fi: 'iyaringu / piyāsu (イヤリング / ピアス)', img: 'clothing/earrings.png' },
    { en: 'gloves', fi: 'tebukuro (手袋)', img: 'clothing/gloves.png' },
    { en: 'handbag', fi: 'handobaggu (ハンドバッグ)', img: 'clothing/handbag.png' },
    { en: 'hat', fi: 'boushi (帽子)', img: 'clothing/hat.png' },
    { en: 'jacket', fi: 'jaketto (ジャケット)', img: 'clothing/jacket.png' },
    { en: 'jeans', fi: 'jiinzu (ジーンズ)', img: 'clothing/jeans.png' },
    { en: 'necklace', fi: 'nekuresu (ネックレス)', img: 'clothing/necklace.png' },
    { en: 'ring', fi: 'yubiwa (指輪)', img: 'clothing/ring.png' },
    { en: 'sandals', fi: 'sandaru (サンダル)', img: 'clothing/sandals.png' },
    { en: 'scarf', fi: 'mafurā (マフラー)', img: 'clothing/scarf.png' },
    { en: 'shirt', fi: 'shatsu (シャツ)', img: 'clothing/shirt.png' },
    { en: 'shoes', fi: 'kutsu (靴)', img: 'clothing/shoes.png' },
    { en: 'shorts', fi: 'shōtsu / hanshaka (ショーツ / 半ズボン)', img: 'clothing/shorts.png' },
    { en: 'skirt', fi: 'sukaato (スカート)', img: 'clothing/skirt.png' },
    { en: 'socks', fi: 'kutsushita (靴下)', img: 'clothing/socks.png' },
    { en: 'sunglasses', fi: 'sangurasu (サングラス)', img: 'clothing/sunglasses.png' },
    { en: 'sweater', fi: 'sētā (セーター)', img: 'clothing/sweater.png' },
    { en: 't-shirt', fi: 'tīshatsu (Tシャツ)', img: 'clothing/t-shirt.png' },
    { en: 'tie', fi: 'nekutai (ネクタイ)', img: 'clothing/tie.png' },
    { en: 'trousers', fi: 'zubon / pantsu (ズボン / パンツ)', img: 'clothing/trousers.png' },
    { en: 'umbrella', fi: 'kasa (傘)', img: 'clothing/umbrella.png' },
    { en: 'wallet', fi: 'saifu (財布)', img: 'clothing/wallet.png' },
    { en: 'watch', fi: 'tokei (時計)', img: 'clothing/watch.png' }
  ]
},

{
  name: '健康 — Kenkō — Health',
  wordsAndImages: [
    { en: 'ambulance', fi: 'kyūkyūsha (救急車)', img: 'health/ambulance.png' },
    { en: 'bacteria', fi: 'saikin (細菌)', img: 'health/bacteria.png' },
    { en: 'bandage', fi: 'hōtai (包帯)', img: 'health/bandage.png' },
    { en: 'cough', fi: 'seki (咳)', img: 'health/cough.png' },
    { en: 'dentist', fi: 'haisha (歯医者)', img: 'health/dentist.png' },
    { en: 'doctor', fi: 'isha (医者)', img: 'health/doctor.png' },
    { en: 'fever', fi: 'netsu (熱)', img: 'health/fever.png' },
    { en: 'headache', fi: 'zutsū (頭痛)', img: 'health/headache.png' },
    { en: 'health center', fi: 'hokensho (保健所)', img: 'health/health_center.png' },
    { en: 'hospital', fi: 'byōin (病院)', img: 'health/hospital.png' },
    { en: 'illness', fi: 'byōki (病気)', img: 'health/illness.png' },
    { en: 'medicine', fi: 'kusuri (薬)', img: 'health/medicine.png' },
    { en: 'nurse', fi: 'kangoshi (看護師)', img: 'health/nurse.png' },
    { en: 'pharmacy', fi: 'yakkyoku (薬局)', img: 'health/pharmacy.png' },
    { en: 'pill', fi: 'piru / jōzai (ピル / 錠剤)', img: 'health/pill.png' },
    { en: 'runny nose', fi: 'hanamizu (鼻水)', img: 'health/runny_nose.png' },
    { en: 'thermometer', fi: 'taionkei (体温計)', img: 'health/thermometer.png' },
    { en: 'vaccine', fi: 'wakuchin (ワクチン)', img: 'health/vaccine.png' },
    { en: 'virus', fi: 'uirusu (ウイルス)', img: 'health/virus.png' }
  ]
},

{
  name: '場所 — Basho — Places',
  wordsAndImages: [
    { en: 'airport', fi: 'kūkō (空港)', img: 'places/airport.png' },
    { en: 'bakery', fi: 'panya (パン屋)', img: 'places/bakery.png' },
    { en: 'bank', fi: 'ginkō (銀行)', img: 'places/bank.png' },
    { en: 'bridge', fi: 'hashi (橋)', img: 'places/bridge.png' },
    { en: 'bus stop', fi: 'basutei (バス停)', img: 'places/bus_stop.png' },
    { en: 'café', fi: 'kafe (カフェ)', img: 'places/café.png' },
    { en: 'fire station', fi: 'shōbōsho (消防署)', img: 'places/fire_station.png' },
    { en: 'gas station', fi: 'gasorinsutando (ガソリンスタンド)', img: 'places/gas_station.png' },
    { en: 'grocery store', fi: 'shokuryōhin-ten (食料品店)', img: 'places/grocery_store.png' },
    { en: 'hospital', fi: 'byōin (病院)', img: 'places/hospital.png' },
    { en: 'hotel', fi: 'hoteru (ホテル)', img: 'places/hotel.png' },
    { en: 'left', fi: 'hidari (左)', img: 'places/left.png' },
    { en: 'library', fi: 'toshokan (図書館)', img: 'places/library.png' },
    { en: 'park', fi: 'kōen (公園)', img: 'places/park.png' },
    { en: 'pharmacy', fi: 'yakkyoku (薬局)', img: 'places/pharmacy.png' },
    { en: 'playground', fi: 'kōen / asobiba (公園 / 遊び場)', img: 'places/playground.png' },
    { en: 'police station', fi: 'kōban (交番)', img: 'places/police_station.png' },
    { en: 'post office', fi: 'yūbinkyoku (郵便局)', img: 'places/post_office.png' },
    { en: 'restaurant', fi: 'resutoran (レストラン)', img: 'places/restaurant.png' },
    { en: 'right', fi: 'migi (右)', img: 'places/right.png' },
    { en: 'road', fi: 'michi (道)', img: 'places/road.png' },
    { en: 'school', fi: 'gakkō (学校)', img: 'places/school.png' },
    { en: 'straight', fi: 'massugu (まっすぐ)', img: 'places/straight.png' },
    { en: 'street', fi: 'dōri (通り)', img: 'places/street.png' },
    { en: 'supermarket', fi: 'suupaa (スーパー)', img: 'places/supermarket.png' },
    { en: 'traffic light', fi: 'shingō (信号)', img: 'places/traffic_light.png' },
    { en: 'train station', fi: 'eki (駅)', img: 'places/train_station.png' },
    { en: 'tunnel', fi: 'tonneru (トンネル)', img: 'places/tunnel.png' }
  ]
},

{
  name: '買い物とお金 — Kaimono to Okane — Shopping and Money',
  wordsAndImages: [
    { en: 'ATM', fi: 'ētiiemu (ATM／現金自動預け払い機)', img: 'shopping_and_money/ATM.png' },
    { en: 'bank', fi: 'ginkō (銀行)', img: 'shopping_and_money/bank.png' },
    { en: 'banknote', fi: 'satsu (札)', img: 'shopping_and_money/banknote.png' },
    { en: 'barcode', fi: 'bākōdo (バーコード)', img: 'shopping_and_money/barcode.png' },
    { en: 'cash', fi: 'genkin (現金)', img: 'shopping_and_money/cash.png' },
    { en: 'cashier', fi: 'reji / kaikei (レジ / 会計)', img: 'shopping_and_money/cashier.png' },
    { en: 'checkout', fi: 'kaikei / chekkuauto (会計 / チェックアウト)', img: 'shopping_and_money/checkout.png' },
    { en: 'coin', fi: 'koin / daka (コイン / 硬貨)', img: 'shopping_and_money/coin.png' },
    { en: 'credit card', fi: 'kurejitto kādo (クレジットカード)', img: 'shopping_and_money/credit_card.png' },
    { en: 'customer', fi: 'okyakusama (お客様)', img: 'shopping_and_money/customer.png' },
    { en: 'euro banknote', fi: 'yūro satsu (ユーロ札)', img: 'shopping_and_money/euro_banknote.png' },
    { en: 'grocery store', fi: 'shokuryōhin-ten (食料品店)', img: 'shopping_and_money/grocery_store.png' },
    { en: 'hardware store', fi: 'dōguya / kaguya (道具屋 / 金物屋)', img: 'shopping_and_money/hardware_store.png' },
    { en: 'kiosk', fi: 'kiosuku (キオスク)', img: 'shopping_and_money/kiosk.png' },
    { en: 'mall', fi: 'mōru (モール)', img: 'shopping_and_money/mall.png' },
    { en: 'money', fi: 'okane (お金)', img: 'shopping_and_money/money.png' },
    { en: 'plastic bag', fi: 'reji bukuro (レジ袋)', img: 'shopping_and_money/plastic_bag.png' },
    { en: 'price tag', fi: 'nedan hyō / puraisutaggu (値段表 / プライスタグ)', img: 'shopping_and_money/price_tag.png' },
    { en: 'purse', fi: 'kozutsumi / saifu (小包 / 財布)', img: 'shopping_and_money/purse.png' },
    { en: 'receipt', fi: 'ryōshūsho (領収書)', img: 'shopping_and_money/receipt.png' },
    { en: 'sale', fi: 'sēru (セール)', img: 'shopping_and_money/sale.png' },
    { en: 'shelf', fi: 'tana (棚)', img: 'shopping_and_money/shelf.png' },
    { en: 'shopping basket', fi: 'kago (買い物かご)', img: 'shopping_and_money/shopping_basket.png' },
    { en: 'shopping cart', fi: 'kātto (カート)', img: 'shopping_and_money/shopping_cart.png' },
    { en: 'shopping mall', fi: 'shōpingu mōru (ショッピングモール)', img: 'shopping_and_money/shopping_mall.png' },
    { en: 'supermarket', fi: 'suupā (スーパー)', img: 'shopping_and_money/supermarket.png' },
    { en: 'wallet', fi: 'saifu (財布)', img: 'shopping_and_money/wallet.png' }
  ]
},
{
  name: '技術 — Gijutsu — Technology',
  wordsAndImages: [
    { en: 'battery', fi: 'denchi (電池)', img: 'technology/battery.png' },
    { en: 'camera', fi: 'kamera (カメラ)', img: 'technology/camera.png' },
    { en: 'charger', fi: 'jūdenki (充電器)', img: 'technology/charger.png' },
    { en: 'computer', fi: 'konpyūta (コンピュータ)', img: 'technology/computer.png' },
    { en: 'email', fi: 'mēru (メール)', img: 'technology/email.png' },
    { en: 'factory', fi: 'kōjō (工場)', img: 'technology/factory.png' },
    { en: 'headphones', fi: 'heddohon (ヘッドホン)', img: 'technology/headphones.png' },
    { en: 'keyboard', fi: 'kībōdo (キーボード)', img: 'technology/keyboard.png' },
    { en: 'laptop', fi: 'nōto pasokon (ノートパソコン)', img: 'technology/laptop.png' },
    { en: 'loudspeaker', fi: 'supīkā (スピーカー)', img: 'technology/loudspeaker.png' },
    { en: 'microphone', fi: 'maiku (マイク)', img: 'technology/microphone.png' },
    { en: 'monitor', fi: 'monitā (モニター)', img: 'technology/monitor.png' },
    { en: 'mouse', fi: 'mausu (マウス)', img: 'technology/mouse.png' },
    { en: 'printer', fi: 'purintā (プリンター)', img: 'technology/printer.png' },
    { en: 'remote control', fi: 'rimokon (リモコン)', img: 'technology/remote_control.png' },
    { en: 'robot', fi: 'robotto (ロボット)', img: 'technology/robot.png' },
    { en: 'smartphone', fi: 'sumātofon (スマートフォン)', img: 'technology/smartphone.png' },
    { en: 'social media', fi: 'sōsharu media (ソーシャルメディア)', img: 'technology/social_media.png' },
    { en: 'USB stick', fi: 'yū-esu-bī memory (USBメモリ)', img: 'technology/USB_stick.png' },
    { en: 'video call', fi: 'bideo tsūwa (ビデオ通話)', img: 'technology/video_call.png' },
    { en: 'website', fi: 'webusaito (ウェブサイト)', img: 'technology/website.png' }
  ]
},

{
  name: '天気と自然 — Tenki to Shizen — Weather and Nature',
  wordsAndImages: [
    { en: 'cloud', fi: 'kumo (雲)', img: 'weather_and_nature/cloud.png' },
    { en: 'cold', fi: 'samui (寒い)', img: 'weather_and_nature/cold.png' },
    { en: 'flower', fi: 'hana (花)', img: 'weather_and_nature/flower.png' },
    { en: 'forest', fi: 'mori (森)', img: 'weather_and_nature/forest.png' },
    { en: 'grass', fi: 'kusa (草)', img: 'weather_and_nature/grass.png' },
    { en: 'hot', fi: 'atsui (暑い)', img: 'weather_and_nature/hot.png' },
    { en: 'lake', fi: 'mizuumi (湖)', img: 'weather_and_nature/lake.png' },
    { en: 'leaf', fi: 'ha (葉)', img: 'weather_and_nature/leaf.png' },
    { en: 'mountain', fi: 'yama (山)', img: 'weather_and_nature/mountain.png' },
    { en: 'mushroom', fi: 'kinoko (キノコ)', img: 'weather_and_nature/mushroom.png' },
    { en: 'rain', fi: 'ame (雨)', img: 'weather_and_nature/rain.png' },
    { en: 'rainbow', fi: 'niji (虹)', img: 'weather_and_nature/rainbow.png' },
    { en: 'river', fi: 'kawa (川)', img: 'weather_and_nature/river.png' },
    { en: 'rock', fi: 'iwa (岩)', img: 'weather_and_nature/rock.png' },
    { en: 'sand', fi: 'suna (砂)', img: 'weather_and_nature/sand.png' },
    { en: 'sea', fi: 'umi (海)', img: 'weather_and_nature/sea.png' },
    { en: 'sky', fi: 'sora (空)', img: 'weather_and_nature/sky.png' },
    { en: 'snow', fi: 'yuki (雪)', img: 'weather_and_nature/snow.png' },
    { en: 'storm', fi: 'arashi (嵐)', img: 'weather_and_nature/storm.png' },
    { en: 'sun', fi: 'taiyō (太陽)', img: 'weather_and_nature/sun.png' },
    { en: 'thermometer', fi: 'taionkei (体温計)', img: 'weather_and_nature/thermometer.png' },
    { en: 'thunder', fi: 'kaminari (雷)', img: 'weather_and_nature/thunder.png' },
    { en: 'tree', fi: 'ki (木)', img: 'weather_and_nature/tree.png' },
    { en: 'warm', fi: 'atatakai (暖かい)', img: 'weather_and_nature/warm.png' },
    { en: 'wind', fi: 'kaze (風)', img: 'weather_and_nature/wind.png' }
  ]
},

{
  name: '趣味 — Shumi — Hobbies',
  wordsAndImages: [
    { en: 'badminton', fi: 'badominton (バドミントン)', img: 'hobbies/badminton.png' },
    { en: 'basketball', fi: 'basukettobōru (バスケットボール)', img: 'hobbies/basketball.png' },
    { en: 'cross-country skiing', fi: 'kurōkantrī sukī (クロスカントリースキー)', img: 'hobbies/crosscountry_skiing.png' },
    { en: 'cycling', fi: 'saikuringu (サイクリング)', img: 'hobbies/cycling.png' },
    { en: 'downhill skiing', fi: 'sukī (スキー)', img: 'hobbies/downhill_skiing.png' },
    { en: 'drums', fi: 'doramu (ドラム)', img: 'hobbies/drums.png' },
    { en: 'football', fi: 'sakkā (サッカー)', img: 'hobbies/football.png' },
    { en: 'guitar', fi: 'gitā (ギター)', img: 'hobbies/guitar.png' },
    { en: 'gym', fi: 'jimu (ジム)', img: 'hobbies/gym.png' },
    { en: 'hiking', fi: 'haikingu (ハイキング)', img: 'hobbies/hiking.png' },
    { en: 'ice hockey', fi: 'aisuhokkē (アイスホッケー)', img: 'hobbies/ice_hockey.png' },
    { en: 'ice skating', fi: 'aisusukēto (アイススケート)', img: 'hobbies/ice_skating.png' },
    { en: 'painting', fi: 'e o kaku (絵を描く)', img: 'hobbies/painting.png' },
    { en: 'piano', fi: 'piano (ピアノ)', img: 'hobbies/piano.png' },
    { en: 'running', fi: 'ranningu (ランニング)', img: 'hobbies/running.png' },
    { en: 'singing', fi: 'utau (歌う)', img: 'hobbies/singing.png' },
    { en: 'snowboarding', fi: 'sunōbōdo (スノーボード)', img: 'hobbies/snowboarding.png' },
    { en: 'swimming', fi: 'oyogu (泳ぐ)', img: 'hobbies/swimming.png' },
    { en: 'tennis', fi: 'tenisu (テニス)', img: 'hobbies/tennis.png' },
    { en: 'video game', fi: 'bideo gēmu (ビデオゲーム)', img: 'hobbies/video_game.png' },
    { en: 'yoga', fi: 'yoga (ヨガ)', img: 'hobbies/yoga.png' }
  ]
},


{
  name: '体の部分 — Karada no Bubun — Body Parts',
  wordsAndImages: [
    { en: 'ankle', fi: 'ashikubi (足首)', img: 'body_parts/ankle.png' },
    { en: 'arm', fi: 'ude (腕)', img: 'body_parts/arm.png' },
    { en: 'back', fi: 'senaka (背中)', img: 'body_parts/back.png' },
    { en: 'chest', fi: 'mune (胸)', img: 'body_parts/chest.png' },
    { en: 'ear', fi: 'mimi (耳)', img: 'body_parts/ear.png' },
    { en: 'elbow', fi: 'hiji (肘)', img: 'body_parts/elbow.png' },
    { en: 'eye', fi: 'me (目)', img: 'body_parts/eye.png' },
    { en: 'face', fi: 'kao (顔)', img: 'body_parts/face.png' },
    { en: 'finger', fi: 'yubi (指)', img: 'body_parts/finger.png' },
    { en: 'foot', fi: 'ashi (足)', img: 'body_parts/foot.png' },
    { en: 'hair', fi: 'kami (髪)', img: 'body_parts/hair.png' },
    { en: 'hand', fi: 'te (手)', img: 'body_parts/hand.png' },
    { en: 'head', fi: 'atama (頭)', img: 'body_parts/head.png' },
    { en: 'heel', fi: 'kakato (踵)', img: 'body_parts/heel.png' },
    { en: 'knee', fi: 'hiza (膝)', img: 'body_parts/knee.png' },
    { en: 'leg', fi: 'ashi (脚)', img: 'body_parts/leg.png' },
    { en: 'mouth', fi: 'kuchi (口)', img: 'body_parts/mouth.png' },
    { en: 'neck', fi: 'kubi (首)', img: 'body_parts/neck.png' },
    { en: 'nose', fi: 'hana (鼻)', img: 'body_parts/nose.png' },
    { en: 'shoulder', fi: 'kata (肩)', img: 'body_parts/shoulder.png' },
    { en: 'stomach', fi: 'onaka (お腹)', img: 'body_parts/stomach.png' },
    { en: 'thumb', fi: 'oyayubi (親指)', img: 'body_parts/thumb.png' },
    { en: 'toe', fi: 'ashiyubi (足指)', img: 'body_parts/toe.png' },
    { en: 'wrist', fi: 'tekubi (手首)', img: 'body_parts/wrist.png' }
  ]
},

{
  name: '数字と時間 — Sūji to Jikan — Numbers and Time',
  wordsAndImages: [
    { en: 'one', fi: 'ichi (一)', img: 'numbers_and_time/one.png' },
    { en: 'two', fi: 'ni (二)', img: 'numbers_and_time/two.png' },
    { en: 'three', fi: 'san (三)', img: 'numbers_and_time/three.png' },
    { en: 'four', fi: 'yon (四)', img: 'numbers_and_time/four.png' },
    { en: 'five', fi: 'go (五)', img: 'numbers_and_time/five.png' },
    { en: 'six', fi: 'roku (六)', img: 'numbers_and_time/six.png' },
    { en: 'seven', fi: 'nana (七)', img: 'numbers_and_time/seven.png' },
    { en: 'eight', fi: 'hachi (八)', img: 'numbers_and_time/eight.png' },
    { en: 'nine', fi: 'kyū (九)', img: 'numbers_and_time/nine.png' },
    { en: 'ten', fi: 'jū (十)', img: 'numbers_and_time/ten.png' },
    { en: 'clock', fi: 'tokei (時計)', img: 'numbers_and_time/clock.png' },
    { en: 'hour', fi: 'jikan (時間)', img: 'numbers_and_time/hour.png' },
    { en: 'minute', fi: 'fun (分)', img: 'numbers_and_time/minute.png' },
    { en: 'second', fi: 'byō (秒)', img: 'numbers_and_time/second.png' },
    { en: 'calendar', fi: 'koyomi (暦)', img: 'numbers_and_time/calendar.png' },
    { en: 'monday', fi: 'getsuyōbi (月曜日)', img: 'numbers_and_time/monday.png' },
    { en: 'tuesday', fi: 'kayōbi (火曜日)', img: 'numbers_and_time/tuesday.png' },
    { en: 'wednesday', fi: 'suiyōbi (水曜日)', img: 'numbers_and_time/wednesday.png' },
    { en: 'thursday', fi: 'mokuyōbi (木曜日)', img: 'numbers_and_time/thursday.png' },
    { en: 'friday', fi: 'kinyōbi (金曜日)', img: 'numbers_and_time/friday.png' },
    { en: 'saturday', fi: 'doyōbi (土曜日)', img: 'numbers_and_time/saturday.png' },
    { en: 'sunday', fi: 'nichiyōbi (日曜日)', img: 'numbers_and_time/sunday.png' },
    { en: 'week', fi: 'shūkan (週間)', img: 'numbers_and_time/week.png' },
    { en: 'weekend', fi: 'shūmatsu (週末)', img: 'numbers_and_time/weekend.png' },
    { en: 'month', fi: 'tsuki (月)', img: 'numbers_and_time/month.png' },
    { en: 'morning', fi: 'asa (朝)', img: 'numbers_and_time/morning.png' },
    { en: 'evening', fi: 'yūgata (夕方)', img: 'numbers_and_time/evening.png' },
    { en: 'night', fi: 'yoru (夜)', img: 'numbers_and_time/night.png' },
    { en: 'spring', fi: 'haru (春)', img: 'numbers_and_time/spring.png' },
    { en: 'summer', fi: 'natsu (夏)', img: 'numbers_and_time/summer.png' },
    { en: 'autumn', fi: 'aki (秋)', img: 'numbers_and_time/autumn.png' },
    { en: 'winter', fi: 'fuyu (冬)', img: 'numbers_and_time/winter.png' }
  ]
}








]